### ISSUE TITLE
expression graphs

### ISSUE THREAD

**Issue by mlubin** [JuliaSmoothOptimizers/AmplNLReader.jl#11]
I'm looking into extracting expression graphs from nl files. I can think of a few possible ways:
1. Use ASL's interface. Not sure how complex this is, but we'll also have to write a friendly C wrapper to call from Julia and figure out how to communicate the data structures.
2. Use @vitaut's new C++ nl reader. It's stream oriented and it doesn't look like it provides an api to extract expression graphs directly. Calling C++ from Julia is possible but not the most stable.
3. Just read the .nl files ourselves and construct julia expressions from them. CC @JackDunnNZ
4. Convert [nl to osil](http://www.coin-or.org/OS/documentation/node41.html), and then we just need an XML reader. Likely that going through OS will be buggy. CC @tkelman

Any suggestions on which approach will be easier?

**Comment by JackDunnNZ** [comment]
I would expect that reading the .nl files directly in Julia would be much simpler than writing them, at least at the level of model that we are capable of writing as .nl from MPB.

**Comment by tkelman** [comment]
I'd also be inclined to go for 3 here. 4 would probably be a pretty small amount of Julia code but would probably need to write a little command-line driver or `extern "C"` wrapper around `OSnl2osil`. I don't know how well-tested the `OSAmplClient` is, but if I had to hazard a guess it would probably be "not very."

Despite the package naming, I feel like the code for 3 would almost fit better in the same repo as AmplNLWriter, if any of the mapping codes could be reused there.

**Comment by dpo** [comment]
I have experience with option 1. Exposing the data structure shouldn't be too hard but the code will break if anything changes in the ASL. Option 3 sounds promising if anyone's willing to go through the effort. Perhaps the new C++ reader can be used to guide the design. The [Writing `.nl` files](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.60.9659&rep=rep1&type=pdf) report should be useful.

**Comment by vitaut** [comment]
Implementing an .nl reader is a fair amount of work if you want a complete and efficient implementation rather than a toy one, way more difficult than writing .nl files. With AMPL/MP you can either construct a Problem instance and use a visitor to traverse expression graphs or build expression trees directly in the format you want using the ProblemBuilder API (the latter is more efficient). Also keep in mind than the .nl format has evolved and the tech report is a bit out of date. Just my two cents.

**Comment by mlubin** [comment]
For my own purposes I'd be happy with a toy implementation that's useful for research purposes (i.e., loading benchmark instances).

**Comment by JackDunnNZ** [comment]
I'm happy to have a look at making a toy implementation that we can extend as needed in future.

@vitaut Is there an up-to-date description of the .nl format available, or a list of changes since the tech report?

**Comment by vitaut** [comment]
@JackDunnNZ Some changes are documented in https://github.com/ampl/mp/blob/master/src/asl/solvers/changes, but they are mixed with the API changes. I recommend using either [ASL](https://github.com/ampl/mp/blob/master/src/asl/solvers/fg_read.c)'s or [MP](https://github.com/ampl/mp/blob/master/include/mp/nl.h)'s NL reader as a reference implementation. The latter might be a bit easier to use because it doesn't mix input with problem construction.

**Comment by mlubin** [comment]
That'd be pretty cool, thanks @JackDunnNZ!

**Comment by baharev** [comment]
@mlubin How far are you with extracting the expression graphs from the .nl files? (I will need something similar too, and it would be a waste of time to implement it twice.)

**Comment by mlubin** [comment]
@baharev I believe @JackDunnNZ looked into this a bit, but I ended up not needing to read .nl files for my own work.

**Comment by JackDunnNZ** [comment]
I started making a toy version that could read and print out simple problems, but somehow can't seem to find it now sorry... It wasn't too complicated though to get it working if you wanted to try it yourself (a few hours to get to where I was up to). 

I basically used the MP NL reader as reference and reimplemented in Julia as suggested earlier. I skipped all the harder parts and just focused on ascii files with only variables and normal linear/nonlinear constraints (no V blocks or more complicated constraint types). It's simple enough to traverse the .nl expressions and convert these node by node into julia expressions, and then you just have to add on the linear terms from the G/J blocks afterwards.

If I do find the code I'll let you know.

**Comment by baharev** [comment]
@JackDunnNZ Thanks. I already wrote a little stack machine in C++ back in 2009 that could handle even the V blocks. Well, sort of, because I ran into undocumented cases with V blocks referring to other V blocks, and with the linear and nonlinear parts split. I gave up the reverse engineering there. Unfortunately, V blocks are essential for my research.

OK, I will open an issue on https://github.com/ampl/mp and if I do not get sufficient help there, I will have to continue reverse engineering the nl file format.

**Comment by baharev** [comment]
@mlubin That's disappointing. See also my answer to Jack just above.

**Comment by mlubin** [comment]
@baharev if you're not tied to AMPL, it's quite easy by the way to get expression graphs out of JuMP.

**Comment by baharev** [comment]
@mlubin I am not sure I follow. I would have to convert a few thousand benchmark problems written in AMPL to some other format. It is out of the question to rewrite those messy problems in JuMP. Does that mean that I am tied to AMPL?

**Comment by mlubin** [comment]
It depends on the complexity of the AMPL models. If they're flattened-out .mod files with no separate data files, you could consider hacking together a parser to convert them to JuMP form. I did something similar (but into Convex.jl form) for my recent work. It's more tedious but less technically intensive than developing an .nl reader.

**Comment by baharev** [comment]
@mlubin These are complicated, messy, non-flat AMPL models, some of them even use the scripting capabilities of AMPL to build the model dynamically when executed. I would have to rewrite a substantial part of AMPL to parse and then interpret them... OK, that pretty much answers my question: Yes, I am tied to AMPL.

**Comment by mlubin** [comment]
Yes, in that case I'd say you're tied to AMPL.
